-- Generated from packages/flavor-engine/src/ingredients.ts.
-- Demo values are hypotheses and require independent culinary validation.

insert into public.preparation_methods (id, name_en, name_uk, profile_multiplier, intensity_multiplier, add_aromas, add_textures) values
  ('raw', 'Raw', 'Без обробки', '{"freshness":1.12,"moisture":1.05}'::jsonb, 1, '{}'::text[], '{}'::text[]),
  ('seared', 'Seared', 'Обсмаження', '{"umami":1.12,"aromaIntensity":1.18,"moisture":0.88,"bitterness":1.08}'::jsonb, 1.12, array['roasted']::text[], array['crisp']::text[]),
  ('roasted', 'Roasted', 'Запікання', '{"sweetness":1.15,"umami":1.1,"aromaIntensity":1.2,"moisture":0.78}'::jsonb, 1.16, array['roasted', 'caramelized']::text[], array['firm']::text[]),
  ('grilled', 'Grilled', 'На грилі', '{"aromaIntensity":1.28,"bitterness":1.18,"umami":1.08,"moisture":0.76,"freshness":0.82}'::jsonb, 1.22, array['smoky', 'roasted']::text[], array['crisp']::text[]),
  ('boiled', 'Boiled', 'Відварювання', '{"aromaIntensity":0.82,"pungency":0.72,"moisture":1.12}'::jsonb, 0.82, '{}'::text[], array['tender']::text[]),
  ('steamed', 'Steamed', 'На парі', '{"freshness":1.06,"aromaIntensity":0.9,"moisture":1.12}'::jsonb, 0.9, '{}'::text[], array['tender']::text[]),
  ('pickled', 'Pickled', 'Маринування', '{"acidity":1.58,"saltiness":1.18,"freshness":1.08,"moisture":1.04}'::jsonb, 1.2, array['vinegar']::text[], '{}'::text[]),
  ('fermented', 'Fermented', 'Ферментація', '{"umami":1.38,"acidity":1.18,"aromaIntensity":1.3}'::jsonb, 1.32, array['fermented']::text[], '{}'::text[]),
  ('smoked', 'Smoked', 'Копчення', '{"aromaIntensity":1.42,"umami":1.12,"freshness":0.72,"moisture":0.88}'::jsonb, 1.34, array['smoky']::text[], '{}'::text[]),
  ('caramelized', 'Caramelized', 'Карамелізація', '{"sweetness":1.52,"bitterness":1.2,"aromaIntensity":1.3,"moisture":0.68}'::jsonb, 1.28, array['caramelized', 'roasted']::text[], array['sticky']::text[]),
  ('pureed', 'Purée', 'Пюре', '{"aromaIntensity":1.04,"moisture":1.04}'::jsonb, 1.02, '{}'::text[], array['silky', 'creamy']::text[]),
  ('sauce', 'Sauce', 'Соус', '{"aromaIntensity":1.08,"moisture":1.08}'::jsonb, 1.08, '{}'::text[], array['silky']::text[])
on conflict (id) do update set
  name_en = excluded.name_en,
  name_uk = excluded.name_uk,
  profile_multiplier = excluded.profile_multiplier,
  intensity_multiplier = excluded.intensity_multiplier,
  add_aromas = excluded.add_aromas,
  add_textures = excluded.add_textures;

insert into public.ingredients (
  id, name_en, name_uk, category_en, category_uk, sensory_profile,
  intensity, texture_intensity, aromas, textures, roles,
  min_share, ideal_share, max_share, preparation_ids,
  source_note, confidence
) values
  ('salmon', 'Salmon', 'Лосось', 'Fish', 'Риба', '{"sweetness":0.8,"acidity":0.2,"saltiness":1.6,"bitterness":0.2,"umami":7.4,"fat":7.8,"pungency":0,"freshness":4.8,"aromaIntensity":6.4,"moisture":7.2}'::jsonb, 6.2, 4.2, array['marine', 'buttery', 'umami']::text[], array['tender', 'flaky']::text[], array['base', 'fat', 'umami']::text[], 28, 48, 78, array['raw', 'seared', 'roasted', 'grilled', 'smoked']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('avocado', 'Avocado', 'Авокадо', 'Fruit', 'Фрукти', '{"sweetness":1.2,"acidity":0.4,"saltiness":0.3,"bitterness":0.4,"umami":2.2,"fat":8.6,"pungency":0,"freshness":4.6,"aromaIntensity":2.8,"moisture":6.4}'::jsonb, 3.2, 2.8, array['green', 'nutty', 'buttery']::text[], array['creamy', 'tender']::text[], array['fat', 'texture']::text[], 8, 18, 34, array['raw', 'grilled', 'pureed']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('mango', 'Mango', 'Манго', 'Fruit', 'Фрукти', '{"sweetness":8.4,"acidity":3.2,"saltiness":0.1,"bitterness":0.2,"umami":0.6,"fat":0.4,"pungency":0.1,"freshness":7.2,"aromaIntensity":7,"moisture":8.4}'::jsonb, 6.4, 3.2, array['tropical', 'fruity', 'floral']::text[], array['juicy', 'tender']::text[], array['sweetener', 'freshness']::text[], 3, 10, 22, array['raw', 'grilled', 'pureed', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('lime', 'Lime', 'Лайм', 'Citrus', 'Цитрусові', '{"sweetness":1.2,"acidity":9.4,"saltiness":0.1,"bitterness":1.4,"umami":0.3,"fat":0.1,"pungency":0.2,"freshness":9,"aromaIntensity":8.2,"moisture":8.8}'::jsonb, 8.6, 1.2, array['citrus', 'green', 'floral']::text[], array['juicy']::text[], array['acid', 'freshness', 'aromatic']::text[], 1, 3.2, 8, array['raw', 'pickled', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('lemon', 'Lemon', 'Лимон', 'Citrus', 'Цитрусові', '{"sweetness":1.4,"acidity":9.1,"saltiness":0.1,"bitterness":1.8,"umami":0.3,"fat":0.1,"pungency":0.1,"freshness":8.8,"aromaIntensity":7.8,"moisture":8.8}'::jsonb, 8.2, 1.2, array['citrus', 'fresh', 'floral']::text[], array['juicy']::text[], array['acid', 'freshness', 'aromatic']::text[], 1, 3.5, 9, array['raw', 'roasted', 'pickled', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('chili', 'Chili', 'Перець чилі', 'Spice', 'Спеції', '{"sweetness":1.4,"acidity":1.1,"saltiness":0.3,"bitterness":0.8,"umami":1,"fat":0.2,"pungency":9.6,"freshness":6.8,"aromaIntensity":8,"moisture":7.4}'::jsonb, 9.4, 2.4, array['green', 'peppery', 'fruity']::text[], array['crisp', 'juicy']::text[], array['spice', 'freshness']::text[], 0.1, 0.8, 3, array['raw', 'roasted', 'grilled', 'pickled', 'fermented', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('cilantro', 'Cilantro', 'Кінза', 'Herb', 'Зелень', '{"sweetness":0.4,"acidity":0.7,"saltiness":0.1,"bitterness":1.2,"umami":0.5,"fat":0.1,"pungency":0.5,"freshness":9.4,"aromaIntensity":8.6,"moisture":7.6}'::jsonb, 7.8, 1.8, array['green', 'citrus', 'herbal']::text[], array['tender']::text[], array['aromatic', 'freshness']::text[], 0.2, 1.8, 5, array['raw', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('sesame', 'Sesame', 'Кунжут', 'Seed', 'Насіння', '{"sweetness":1.2,"acidity":0.1,"saltiness":0.4,"bitterness":1.2,"umami":4.4,"fat":7.4,"pungency":0,"freshness":1.2,"aromaIntensity":7.6,"moisture":1.2}'::jsonb, 6.8, 7.4, array['nutty', 'roasted', 'earthy']::text[], array['crunchy']::text[], array['fat', 'umami', 'texture', 'aromatic']::text[], 0.3, 2.2, 6, array['raw', 'roasted', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('ginger', 'Ginger', 'Імбир', 'Aromatic', 'Ароматичні', '{"sweetness":1.2,"acidity":1,"saltiness":0.1,"bitterness":1,"umami":1.2,"fat":0.1,"pungency":7.8,"freshness":8.4,"aromaIntensity":8.8,"moisture":7.2}'::jsonb, 8.8, 3.8, array['citrus', 'spicy', 'woody']::text[], array['fibrous', 'crisp']::text[], array['spice', 'aromatic', 'freshness']::text[], 0.3, 1.8, 5, array['raw', 'seared', 'pickled', 'fermented', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('cucumber', 'Cucumber', 'Огірок', 'Vegetable', 'Овочі', '{"sweetness":1.2,"acidity":0.7,"saltiness":0.1,"bitterness":0.3,"umami":0.3,"fat":0.1,"pungency":0,"freshness":9.6,"aromaIntensity":2.8,"moisture":9.8}'::jsonb, 2.2, 7.2, array['green', 'watery', 'fresh']::text[], array['crisp', 'juicy']::text[], array['freshness', 'texture']::text[], 5, 16, 34, array['raw', 'pickled', 'pureed']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('soy_sauce', 'Soy sauce', 'Соєвий соус', 'Seasoning', 'Приправи', '{"sweetness":1.2,"acidity":1.1,"saltiness":9.2,"bitterness":0.9,"umami":9.4,"fat":0.1,"pungency":0.2,"freshness":0.4,"aromaIntensity":8.4,"moisture":7.8}'::jsonb, 9.2, 1, array['fermented', 'umami', 'roasted']::text[], array['silky']::text[], array['umami', 'sauce']::text[], 0.5, 2.4, 6, array['fermented', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('miso', 'Miso', 'Місо', 'Fermented', 'Ферментовані', '{"sweetness":2.4,"acidity":1.2,"saltiness":7.8,"bitterness":1,"umami":9.6,"fat":2.2,"pungency":0.1,"freshness":0.3,"aromaIntensity":8.8,"moisture":5.2}'::jsonb, 9.2, 2.8, array['fermented', 'umami', 'nutty']::text[], array['creamy', 'sticky']::text[], array['umami', 'sauce']::text[], 0.5, 2.8, 7, array['fermented', 'sauce', 'roasted']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('butter', 'Butter', 'Вершкове масло', 'Dairy', 'Молочні', '{"sweetness":0.6,"acidity":0.2,"saltiness":1.2,"bitterness":0.1,"umami":2.8,"fat":9.8,"pungency":0,"freshness":0.2,"aromaIntensity":4.2,"moisture":1.6}'::jsonb, 4.8, 2.2, array['buttery', 'dairy', 'creamy']::text[], array['creamy', 'silky']::text[], array['fat', 'sauce']::text[], 1, 5.5, 14, array['raw', 'seared', 'sauce', 'caramelized']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('mayonnaise', 'Mayonnaise', 'Майонез', 'Sauce', 'Соуси', '{"sweetness":0.8,"acidity":2.3,"saltiness":2.2,"bitterness":0.2,"umami":2.4,"fat":9.2,"pungency":0.1,"freshness":0.6,"aromaIntensity":3.4,"moisture":4.6}'::jsonb, 4.6, 2.4, array['creamy', 'egg', 'vinegar']::text[], array['creamy', 'silky']::text[], array['fat', 'sauce']::text[], 2, 7, 18, array['sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('duck', 'Duck', 'Качка', 'Meat', 'М’ясо', '{"sweetness":0.6,"acidity":0.1,"saltiness":1.2,"bitterness":0.2,"umami":7.8,"fat":8.2,"pungency":0,"freshness":1.2,"aromaIntensity":7.2,"moisture":5.6}'::jsonb, 7.4, 5.4, array['meaty', 'gamey', 'buttery']::text[], array['tender', 'firm', 'juicy']::text[], array['base', 'fat', 'umami']::text[], 30, 52, 82, array['seared', 'roasted', 'grilled', 'smoked']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('cherry', 'Cherry', 'Вишня', 'Fruit', 'Фрукти', '{"sweetness":7,"acidity":6.4,"saltiness":0.1,"bitterness":0.7,"umami":0.6,"fat":0.2,"pungency":0,"freshness":7.4,"aromaIntensity":7.4,"moisture":8.8}'::jsonb, 6.8, 3.4, array['red-fruit', 'floral', 'almond']::text[], array['juicy', 'tender']::text[], array['acid', 'sweetener', 'freshness']::text[], 3, 11, 24, array['raw', 'roasted', 'pickled', 'sauce', 'caramelized']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('rosemary', 'Rosemary', 'Розмарин', 'Herb', 'Зелень', '{"sweetness":0.2,"acidity":0.2,"saltiness":0.1,"bitterness":3.2,"umami":0.5,"fat":0.4,"pungency":1.2,"freshness":4.6,"aromaIntensity":9.4,"moisture":2.2}'::jsonb, 9.6, 3.8, array['herbal', 'pine', 'woody']::text[], array['fibrous']::text[], array['aromatic']::text[], 0.05, 0.4, 1.5, array['raw', 'roasted', 'grilled', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('thyme', 'Thyme', 'Чебрець', 'Herb', 'Зелень', '{"sweetness":0.2,"acidity":0.3,"saltiness":0.1,"bitterness":2.1,"umami":0.6,"fat":0.2,"pungency":0.6,"freshness":5.2,"aromaIntensity":8.4,"moisture":2.2}'::jsonb, 8.2, 2.8, array['herbal', 'woody', 'floral']::text[], array['tender', 'fibrous']::text[], array['aromatic']::text[], 0.08, 0.5, 1.8, array['raw', 'roasted', 'grilled', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('orange', 'Orange', 'Апельсин', 'Citrus', 'Цитрусові', '{"sweetness":7.2,"acidity":5.4,"saltiness":0.1,"bitterness":0.8,"umami":0.3,"fat":0.1,"pungency":0,"freshness":8.2,"aromaIntensity":7.2,"moisture":9.2}'::jsonb, 6.6, 2.8, array['citrus', 'fruity', 'floral']::text[], array['juicy']::text[], array['acid', 'sweetener', 'freshness']::text[], 2, 8, 20, array['raw', 'roasted', 'sauce', 'caramelized']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('balsamic', 'Balsamic vinegar', 'Бальзамічний оцет', 'Vinegar', 'Оцет', '{"sweetness":5.4,"acidity":8.2,"saltiness":0.2,"bitterness":1.1,"umami":2.2,"fat":0.1,"pungency":0,"freshness":1.4,"aromaIntensity":7.8,"moisture":7.6}'::jsonb, 8.2, 1, array['vinegar', 'dark-fruit', 'caramelized']::text[], array['silky']::text[], array['acid', 'sweetener', 'sauce']::text[], 0.3, 1.8, 5, array['sauce', 'caramelized']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('red_wine', 'Red wine', 'Червоне вино', 'Wine', 'Вино', '{"sweetness":2.4,"acidity":6.2,"saltiness":0.1,"bitterness":3.2,"umami":2.2,"fat":0,"pungency":0.3,"freshness":1.8,"aromaIntensity":7.8,"moisture":8.8}'::jsonb, 7.4, 1, array['red-fruit', 'tannic', 'earthy']::text[], array['silky']::text[], array['acid', 'aromatic', 'sauce']::text[], 2, 8, 22, array['raw', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('chicken', 'Chicken', 'Курка', 'Meat', 'М’ясо', '{"sweetness":0.4,"acidity":0.1,"saltiness":1.1,"bitterness":0.1,"umami":5.8,"fat":3.4,"pungency":0,"freshness":2.2,"aromaIntensity":4.4,"moisture":6.2}'::jsonb, 4.4, 5, array['meaty', 'mild', 'brothy']::text[], array['tender', 'fibrous']::text[], array['base', 'umami']::text[], 32, 56, 84, array['seared', 'roasted', 'grilled', 'boiled', 'steamed', 'smoked']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('cream', 'Cream', 'Вершки', 'Dairy', 'Молочні', '{"sweetness":1.8,"acidity":0.5,"saltiness":0.5,"bitterness":0.1,"umami":2.2,"fat":8.8,"pungency":0,"freshness":0.3,"aromaIntensity":3.2,"moisture":6.8}'::jsonb, 3.8, 2, array['dairy', 'creamy', 'buttery']::text[], array['creamy', 'silky']::text[], array['fat', 'sauce']::text[], 3, 11, 28, array['raw', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('mushrooms', 'Mushrooms', 'Гриби', 'Fungi', 'Гриби', '{"sweetness":0.8,"acidity":0.2,"saltiness":0.4,"bitterness":1.2,"umami":8.4,"fat":0.6,"pungency":0,"freshness":2.2,"aromaIntensity":7.4,"moisture":8.8}'::jsonb, 6.8, 5.8, array['earthy', 'umami', 'woody']::text[], array['tender', 'firm', 'juicy']::text[], array['umami', 'base', 'texture']::text[], 6, 18, 38, array['raw', 'seared', 'roasted', 'grilled', 'boiled', 'pureed']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('garlic', 'Garlic', 'Часник', 'Aromatic', 'Ароматичні', '{"sweetness":1.6,"acidity":0.4,"saltiness":0.1,"bitterness":1,"umami":3.8,"fat":0.1,"pungency":7.2,"freshness":4.2,"aromaIntensity":9.2,"moisture":6.2}'::jsonb, 9.2, 3.4, array['sulfurous', 'savory', 'roasted']::text[], array['crisp', 'creamy']::text[], array['aromatic', 'spice', 'umami']::text[], 0.2, 1.4, 4, array['raw', 'seared', 'roasted', 'grilled', 'fermented', 'pureed', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('rice_vinegar', 'Rice vinegar', 'Рисовий оцет', 'Vinegar', 'Оцет', '{"sweetness":1.8,"acidity":8.8,"saltiness":0.1,"bitterness":0.3,"umami":0.6,"fat":0,"pungency":0,"freshness":4.2,"aromaIntensity":5.2,"moisture":9.2}'::jsonb, 7.2, 1, array['vinegar', 'clean', 'fermented']::text[], array['silky']::text[], array['acid', 'sauce']::text[], 0.4, 2, 6, array['sauce', 'pickled', 'fermented']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('parmesan', 'Parmesan', 'Пармезан', 'Cheese', 'Сир', '{"sweetness":1,"acidity":1.2,"saltiness":7.8,"bitterness":1.2,"umami":9.6,"fat":7.2,"pungency":0,"freshness":0.2,"aromaIntensity":8.8,"moisture":2.2}'::jsonb, 9, 7.2, array['dairy', 'nutty', 'umami', 'aged']::text[], array['firm', 'crunchy']::text[], array['umami', 'fat', 'texture']::text[], 0.8, 3.5, 10, array['raw', 'roasted', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('blue_cheese', 'Blue cheese', 'Блакитний сир', 'Cheese', 'Сир', '{"sweetness":0.6,"acidity":1.8,"saltiness":7.2,"bitterness":2.4,"umami":8.8,"fat":8.4,"pungency":1.2,"freshness":0.1,"aromaIntensity":9.8,"moisture":3.6}'::jsonb, 9.8, 4.4, array['dairy', 'funky', 'aged', 'earthy']::text[], array['creamy', 'crumbly']::text[], array['umami', 'fat', 'aromatic']::text[], 0.6, 2.8, 7, array['raw', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('potato', 'Potato', 'Картопля', 'Vegetable', 'Овочі', '{"sweetness":1.2,"acidity":0.1,"saltiness":0.2,"bitterness":0.2,"umami":2.8,"fat":0.3,"pungency":0,"freshness":1.2,"aromaIntensity":2.2,"moisture":7.6}'::jsonb, 2.2, 6.2, array['earthy', 'starchy', 'mild']::text[], array['creamy', 'firm', 'crisp']::text[], array['base', 'texture']::text[], 12, 28, 58, array['boiled', 'roasted', 'grilled', 'pureed']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('pork', 'Pork', 'Свинина', 'Meat', 'М’ясо', '{"sweetness":0.7,"acidity":0.1,"saltiness":1.1,"bitterness":0.2,"umami":7,"fat":7.2,"pungency":0,"freshness":1.1,"aromaIntensity":6.2,"moisture":5.8}'::jsonb, 6.4, 5.8, array['meaty', 'savory', 'fatty']::text[], array['tender', 'fibrous', 'juicy']::text[], array['base', 'fat', 'umami']::text[], 30, 54, 82, array['seared', 'roasted', 'grilled', 'boiled', 'smoked']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('apple', 'Apple', 'Яблуко', 'Fruit', 'Фрукти', '{"sweetness":6.8,"acidity":4.8,"saltiness":0.1,"bitterness":0.4,"umami":0.3,"fat":0.1,"pungency":0,"freshness":8.4,"aromaIntensity":5.8,"moisture":9.1}'::jsonb, 5.2, 7.2, array['fruity', 'green', 'floral']::text[], array['crisp', 'juicy']::text[], array['sweetener', 'acid', 'freshness', 'texture']::text[], 3, 11, 26, array['raw', 'roasted', 'grilled', 'pickled', 'pureed', 'sauce', 'caramelized']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('beetroot', 'Beetroot', 'Буряк', 'Vegetable', 'Овочі', '{"sweetness":6.2,"acidity":1.1,"saltiness":0.4,"bitterness":1.4,"umami":3.2,"fat":0.2,"pungency":0,"freshness":3.2,"aromaIntensity":6.4,"moisture":8.2}'::jsonb, 6.2, 6, array['earthy', 'sweet', 'mineral']::text[], array['firm', 'juicy', 'tender']::text[], array['base', 'sweetener', 'texture']::text[], 7, 18, 38, array['raw', 'roasted', 'boiled', 'pickled', 'pureed']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('tahini', 'Tahini', 'Тахіні', 'Seed paste', 'Паста з насіння', '{"sweetness":1.2,"acidity":0.2,"saltiness":0.5,"bitterness":3.2,"umami":4.8,"fat":8.6,"pungency":0,"freshness":0.4,"aromaIntensity":7.4,"moisture":2.8}'::jsonb, 7.4, 2.2, array['sesame', 'nutty', 'roasted']::text[], array['creamy', 'sticky']::text[], array['fat', 'umami', 'sauce']::text[], 1, 5, 13, array['raw', 'roasted', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('pomegranate', 'Pomegranate', 'Гранат', 'Fruit', 'Фрукти', '{"sweetness":6.4,"acidity":6.8,"saltiness":0.1,"bitterness":1.2,"umami":0.4,"fat":0.1,"pungency":0,"freshness":8.2,"aromaIntensity":7.2,"moisture":8.8}'::jsonb, 6.6, 7.8, array['red-fruit', 'floral', 'tannic']::text[], array['juicy', 'crunchy']::text[], array['acid', 'sweetener', 'freshness', 'texture']::text[], 1, 5, 14, array['raw', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('cauliflower', 'Cauliflower', 'Цвітна капуста', 'Vegetable', 'Овочі', '{"sweetness":1.4,"acidity":0.3,"saltiness":0.3,"bitterness":0.7,"umami":3.8,"fat":0.2,"pungency":0,"freshness":4.4,"aromaIntensity":3.6,"moisture":8.2}'::jsonb, 3.8, 6.8, array['vegetal', 'nutty', 'sulfurous']::text[], array['firm', 'crisp', 'tender']::text[], array['base', 'texture']::text[], 18, 38, 72, array['raw', 'roasted', 'grilled', 'boiled', 'steamed', 'pureed']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('walnut', 'Walnut', 'Волоський горіх', 'Nut', 'Горіхи', '{"sweetness":1.3,"acidity":0.2,"saltiness":0.2,"bitterness":3.2,"umami":3.8,"fat":8.8,"pungency":0,"freshness":0.3,"aromaIntensity":7.8,"moisture":1.2}'::jsonb, 7.4, 8.8, array['nutty', 'woody', 'earthy']::text[], array['crunchy', 'firm']::text[], array['fat', 'texture', 'aromatic']::text[], 0.8, 3.8, 10, array['raw', 'roasted', 'pureed', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('honey', 'Honey', 'Мед', 'Sweetener', 'Підсолоджувачі', '{"sweetness":9.8,"acidity":0.7,"saltiness":0.1,"bitterness":0.2,"umami":0.4,"fat":0,"pungency":0,"freshness":0.4,"aromaIntensity":6.4,"moisture":3.2}'::jsonb, 7.2, 2.4, array['floral', 'caramelized', 'sweet']::text[], array['sticky', 'silky']::text[], array['sweetener', 'sauce']::text[], 0.2, 1.8, 5, array['raw', 'sauce', 'caramelized']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55),
  ('black_pepper', 'Black pepper', 'Чорний перець', 'Spice', 'Спеції', '{"sweetness":0.2,"acidity":0.1,"saltiness":0.1,"bitterness":2.8,"umami":0.8,"fat":0.1,"pungency":7.4,"freshness":1.2,"aromaIntensity":8.8,"moisture":0.8}'::jsonb, 9, 2, array['peppery', 'woody', 'citrus']::text[], array['crunchy']::text[], array['spice', 'aromatic']::text[], 0.05, 0.35, 1.2, array['raw', 'roasted', 'sauce']::text[], 'MVP expert seed; validate with culinary reviewers', 0.55)
on conflict (id) do update set
  name_en = excluded.name_en,
  name_uk = excluded.name_uk,
  category_en = excluded.category_en,
  category_uk = excluded.category_uk,
  sensory_profile = excluded.sensory_profile,
  intensity = excluded.intensity,
  texture_intensity = excluded.texture_intensity,
  aromas = excluded.aromas,
  textures = excluded.textures,
  roles = excluded.roles,
  min_share = excluded.min_share,
  ideal_share = excluded.ideal_share,
  max_share = excluded.max_share,
  preparation_ids = excluded.preparation_ids,
  source_note = excluded.source_note,
  confidence = excluded.confidence;

insert into public.ingredient_pairings (
  ingredient_a_id, ingredient_b_id, explicit_adjustment, confidence, source_note
) values
  ('lime', 'salmon', 22, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('lemon', 'salmon', 21, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('avocado', 'salmon', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('mango', 'salmon', 10, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cilantro', 'salmon', 14, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('salmon', 'sesame', 14, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('ginger', 'salmon', 15, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cucumber', 'salmon', 15, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('salmon', 'soy_sauce', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('miso', 'salmon', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('avocado', 'lime', 24, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('avocado', 'lemon', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('avocado', 'mango', 12, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('avocado', 'cilantro', 16, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('avocado', 'chili', 13, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('lime', 'mango', 23, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('chili', 'mango', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cilantro', 'mango', 14, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('ginger', 'mango', 14, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('chili', 'lime', 16, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cilantro', 'lime', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('ginger', 'soy_sauce', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('sesame', 'soy_sauce', 19, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('miso', 'sesame', 17, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cherry', 'duck', 25, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('duck', 'orange', 22, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('duck', 'rosemary', 17, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('duck', 'thyme', 17, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('duck', 'red_wine', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('balsamic', 'duck', 16, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('balsamic', 'cherry', 21, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cherry', 'red_wine', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cherry', 'rosemary', 11, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('chicken', 'cream', 17, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('chicken', 'mushrooms', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('chicken', 'garlic', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('chicken', 'thyme', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cream', 'mushrooms', 21, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cream', 'garlic', 14, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('garlic', 'mushrooms', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('mushrooms', 'thyme', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('mushrooms', 'parmesan', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('apple', 'pork', 23, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('honey', 'pork', 13, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('pork', 'rosemary', 15, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('beetroot', 'blue_cheese', 23, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('beetroot', 'walnut', 22, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('balsamic', 'beetroot', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cauliflower', 'tahini', 23, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cauliflower', 'pomegranate', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cauliflower', 'parmesan', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('lemon', 'tahini', 22, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('garlic', 'tahini', 17, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('pomegranate', 'walnut', 15, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('apple', 'blue_cheese', 22, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('blue_cheese', 'honey', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('blue_cheese', 'walnut', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('butter', 'potato', 20, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('garlic', 'potato', 18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('potato', 'rosemary', 17, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('blue_cheese', 'salmon', -18, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('mango', 'rosemary', -14, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cucumber', 'duck', -10, 0.55, 'MVP expert seed; validate with culinary reviewers'),
  ('cherry', 'soy_sauce', -8, 0.55, 'MVP expert seed; validate with culinary reviewers')
on conflict (ingredient_a_id, ingredient_b_id) do update set
  explicit_adjustment = excluded.explicit_adjustment,
  confidence = excluded.confidence,
  source_note = excluded.source_note;
